# ===== DataSource (PostgreSQL) =====
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=todo_user
spring.datasource.password=secret123
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway сам создаст таблицы — убираем автогенерацию Hibernate
spring.jpa.hibernate.ddl-auto=validate

# ===== Redis =====
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis123

# ===== Cache =====
spring.cache.type=redis
spring.cache.redis.time-to-live=600000   # 10 минут в миллисекундах